export default {
  'query-ssr': ['TanStack Query · 서버 렌더링', 'https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr'],
  'query-api': ['TanStack Query · useQuery', 'https://tanstack.com/query/latest/docs/framework/react/reference/useQuery'],
  'query-invalidation': ['TanStack Query · 캐시 무효화', 'https://tanstack.com/query/latest/docs/framework/react/guides/query-invalidation'],
  'query-optimistic': ['TanStack Query · 낙관적 업데이트', 'https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates'],
  'query-prefetch': ['TanStack Query · 프리패칭', 'https://tanstack.com/query/latest/docs/framework/react/guides/prefetching'],
  'next-layout': ['Next.js · Layout', 'https://nextjs.org/docs/app/api-reference/file-conventions/layout'],
  'next-revalidate': ['Next.js · revalidatePath', 'https://nextjs.org/docs/app/api-reference/functions/revalidatePath'],
  'next-refresh': ['Next.js · router.refresh', 'https://nextjs.org/docs/app/api-reference/functions/use-router'],
  'next-cookies': ['Next.js · cookies', 'https://nextjs.org/docs/app/api-reference/functions/cookies'],
  'next-dynamic': ['Next.js · Dynamic Segments', 'https://nextjs.org/docs/app/api-reference/file-conventions/dynamic-routes'],
  'cookie': ['MDN · Set-Cookie', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie'],
  'cors': ['MDN · CORS', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS'],
  'sanitize': ['sanitize-html · 허용 목록 설정', 'https://github.com/apostrophecms/sanitize-html'],
  'openapi': ['openapi-typescript · 타입 생성', 'https://openapi-ts.dev/introduction'],
  'federation': ['Webpack · Module Federation', 'https://webpack.js.org/concepts/module-federation/'],
  'postmessage': ['MDN · postMessage', 'https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage'],
  'kubb': ['Kubb · OpenAPI 코드 생성', 'https://kubb.dev/'],
  'msw': ['MSW · 네트워크 Mock', 'https://mswjs.io/docs/'],
  'faker': ['Faker · 더미 데이터', 'https://fakerjs.dev/guide/'],
  'nativewind': ['NativeWind · 공식 문서', 'https://www.nativewind.dev/'],
  'github-packages': ['GitHub Packages · npm registry', 'https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry'],
  'i18next': ['i18next · API', 'https://www.i18next.com/overview/api'],
  'jspdf': ['jsPDF · 공식 저장소', 'https://github.com/parallax/jsPDF'],
  'cva': ['CVA · Variants', 'https://cva.style/'],
  'safe-area': ['MDN · env()와 안전 영역', 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/env'],
  'echarts': ['ECharts · 차트 크기와 정리', 'https://echarts.apache.org/handbook/en/concepts/chart-size/'],
  'react-input': ['React · input', 'https://react.dev/reference/react-dom/components/input'],
  'axios-interceptors': ['Axios · Interceptors', 'https://axios-http.com/docs/interceptors'],
  'lint-staged': ['lint-staged · 공식 저장소', 'https://github.com/lint-staged/lint-staged'],
  'husky': ['Husky · Git hooks', 'https://typicode.github.io/husky/'],
  'socketio': ['Socket.IO · 개요', 'https://socket.io/docs/v4/'],
  'socketio-scale': ['Socket.IO · 다중 서버', 'https://socket.io/docs/v4/using-multiple-nodes/'],
  'telegram': ['Telegram · Bot API FAQ', 'https://core.telegram.org/bots/faq'],
  'd3': ['D3 · 데이터 시각화', 'https://d3js.org/what-is-d3'],
};
